route:
  receiver: rollback-webhook
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 5m
  routes:
    - match:
        action: rollback
      receiver: rollback-webhook

receivers:
  - name: rollback-webhook
    webhook_configs:
      - url: http://rollback_ctrl:8000/alert
        send_resolved: true
